name: KEDE_APP
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paket yang kita tambahkan
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Bagian ini adalah yang paling penting.
# Pastikan spasinya sama persis.
flutter:
  # 'uses-material-design' punya 2 spasi
  uses-material-design: true

  # 'assets:' punya 2 spasi
  assets:
    # Baris path ini punya 4 spasi
    - assets/images/
    # Baris path ini juga punya 4 spasi (SEJAJAR)
    - assets/icons/